[package]
name = "ll-testkit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ed25519-dalek.workspace = true
getrandom.workspace = true
hex.workspace = true
tempfile.workspace = true
thiserror.workspace = true
uuid.workspace = true
zeroize.workspace = true

[lints]
workspace = true
