[package]
name = "ll-crypto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
argon2.workspace = true
base32ct.workspace = true
blake3.workspace = true
chacha20poly1305.workspace = true
ed25519-dalek.workspace = true
getrandom.workspace = true
hmac.workspace = true
hkdf.workspace = true
ll-protocol = { path = "../ll-protocol", version = "1.0.0" }
minicbor.workspace = true
sha2.workspace = true
snow.workspace = true
subtle.workspace = true
thiserror.workspace = true
x25519-dalek.workspace = true
zeroize.workspace = true

[dev-dependencies]
hex.workspace = true
ll-testkit = { path = "../ll-testkit", version = "1.0.0" }
serde_json.workspace = true
tempfile.workspace = true

[lints]
workspace = true
