[package]
name = "ll-crypto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
argon2.workspace = true
base32ct.workspace = true
blake3.workspace = true
ed25519-dalek.workspace = true
getrandom.workspace = true
hmac.workspace = true
ll-protocol = { path = "../ll-protocol", version = "0.1.0" }
sha2.workspace = true
snow.workspace = true
subtle.workspace = true
thiserror.workspace = true
x25519-dalek.workspace = true
zeroize.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
